#!/usr/bin/zsh

# make vim default editor
if [ -n "$(command -v nvim)" ]; then
  export EDITOR='nvim'
else
  export EDITOR='vim'
fi

# default browser
export BROWSER='brave'

# default file-browser
export FILEMANAGER="spacefm"

# NPM and NODE XDG compliance
export NODE_REPL_HISTORY="$XDG_DATA_HOME/node_repl_history"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"

export LD_LIBRARY_PATH=/usr/local/lib:/usr/include
export PKG_CONFIG_PATH=/usr/share/pkgconfig:/usr/lib/pkgconfig

# Locale in english
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_COLLATE=en_US.UTF-8
export LC_CTYPE=C

# Make local executables visible
export PATH="$HOME/.local/bin:$PATH"

# Rust
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export PATH="$XDG_DATA_HOME/cargo/bin:$PATH"

# Doom emacs
export PATH="$XDG_CONFIG_HOME/emacs/bin:$PATH"
export DOOMDIR="$XDG_CONFIG_HOME/doom"

# Mongo Memory Server (FIXME Just a hotfix)
export MONGOMS_SYSTEM_BINARY="$(command -v mongod)"

# Tramp
[ $TERM = "dumb" ] && unsetopt zle && PS1='$ '

# SSH hack
alias ssh='TERM=xterm-256color ssh'
